version: 2.1

orbs:
  codecov: codecov/codecov@3.1.1
  node: circleci/node@4.7

workflows:
  test-and-upload-result:
    jobs:
      - node/test:
          version: 12.22.0
          pkg-manager: yarn
          post-steps:
            - codecov/upload
