version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.1.1

workflows:
  sample:
    jobs:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - node/test:
          post-steps:
            - codecov/upload
